---
version: '3'
services:
  orcpub:
    build:
      context: docker/orcpub
      args:
        REPO: Orcpub
        BRANCH: develop
    image: demonsthere/orcpub:orcpub
    environment:
      PORT: 8890
      EMAIL_SERVER_URL: test.mailu.io
      EMAIL_ACCESS_KEY: admin@test.mailu.io
      EMAIL_SECRET_KEY: letmein
      EMAIL_SERVER_PORT: 587
      DATOMIC_URL: datomic:free://datomic:4334/orcpub
    depends_on:
      - datomic
    restart: always
  datomic:
    image: demonsthere/orcpub:datomic
    volumes:
      - ./data:/data
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - orcpub
