name: Continuous Integration

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest
          boot: latest
      - name: Run tests
        run: lein test